source 'https://rubygems.org'

gem 'after_do'
gem 'rspec', '~> 2.12'
gem 'factory_girl', '~>4.1.0'
gem 'timecop'
gem 'guard-rspec', '~> 2.3.3'
gem 'rb-inotify', '~> 0.8.8'
gem 'libnotify'
gem 'timecop'
gem 'simplecov'